from db import conectar

#verifica se a tabela contato existe, senão, cria ela
def criar_tabela_contato():
    conexao = conectar()
    if not conexao:
        return

    cursor = None
    try:
        cursor = conexao.cursor()

        cursor.execute("""
            SELECT COUNT(*)
            FROM USER_TABLES
            WHERE TABLE_NAME = 'CONTATO'
        """)
        resultado = cursor.fetchone()

        if resultado and resultado[0] > 0:
            print("A tabela contato já existe.")
            return

        cursor.execute("""
            CREATE TABLE CONTATO (
                ID_CONTATO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TP_CONTATO VARCHAR2(20) NOT NULL,
                NM_CONTATO VARCHAR2(100) NOT NULL,
                TP_DOCUMENTO VARCHAR2(20) NOT NULL,
                NR_DOCUMENTO VARCHAR2(30) NOT NULL,
                DS_EMAIL VARCHAR2(100),
                NR_CEP VARCHAR2(8),
                NR_CRO VARCHAR2(30),
                DS_ESPECIALIDADE VARCHAR2(100)
            )
        """)

        conexao.commit()
        print("Tabela CONTATO criada com sucesso.")

    except Exception as e:
        print(f"Erro ao verificar/criar tabela CONTATO: {e}")
    finally:
        if cursor:
            cursor.close()
        conexao.close()

#insere um contato na tabela
def inserir_contato(tipo_contato, nome, tipo_documento, numero_documento, email, cep, cro="", especialidade=""):
    conexao = conectar()
    if not conexao:
        return

    cursor = None
    try:
        cursor = conexao.cursor()

        sql = """
            INSERT INTO CONTATO
            (TP_CONTATO, NM_CONTATO, TP_DOCUMENTO, NR_DOCUMENTO, DS_EMAIL, NR_CEP, NR_CRO, DS_ESPECIALIDADE)
            VALUES (:1, :2, :3, :4, :5, :6, :7, :8)
        """
        cursor.execute(sql, (
            tipo_contato,
            nome,
            tipo_documento,
            numero_documento,
            email,
            cep,
            cro,
            especialidade,
        ))
        conexao.commit()
        print(f"{tipo_contato.title()} cadastrado com sucesso.")
    except Exception as e:
        print(f"Erro ao inserir contato: {e}")
    finally:
        if cursor:
            cursor.close()
        conexao.close()

#lista todos os contatos de um tipo na tabela
def listar_contatos(tipo_contato):
    conexao = conectar()
    if not conexao:
        return []

    cursor = None
    try:
        cursor = conexao.cursor()
        cursor.execute("""
            SELECT ID_CONTATO, TP_CONTATO, NM_CONTATO, TP_DOCUMENTO, NR_DOCUMENTO, DS_EMAIL,
                   NR_CEP, NR_CRO, DS_ESPECIALIDADE
            FROM CONTATO
            WHERE UPPER(TP_CONTATO) = UPPER(:1)
            ORDER BY ID_CONTATO
        """, (tipo_contato,))
        resultados = cursor.fetchall()

        contatos = []
        for row in resultados:
            contatos.append({
                "id_contato": row[0],
                "tp_contato": row[1],
                "nm_contato": row[2],
                "tp_documento": row[3],
                "nr_documento": row[4],
                "ds_email": row[5],
                "nr_cep": row[6],
                "nr_cro": row[7],
                "ds_especialidade": row[8]
            })

        return contatos
    except Exception as e:
        print(f"Erro ao listar contatos: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        conexao.close()

#procura um contato pelo id interno
def buscar_contato_por_id(id_contato):
    conexao = conectar()
    if not conexao:
        return None

    cursor = None
    try:
        cursor = conexao.cursor()
        cursor.execute("""
            SELECT ID_CONTATO, TP_CONTATO, NM_CONTATO, TP_DOCUMENTO, NR_DOCUMENTO, DS_EMAIL,
                   NR_CEP, NR_CRO, DS_ESPECIALIDADE
            FROM CONTATO
            WHERE ID_CONTATO = :1
        """, (id_contato,))
        row = cursor.fetchone()

        if not row:
            return None

        return {
            "id_contato": row[0],
            "tp_contato": row[1],
            "nm_contato": row[2],
            "tp_documento": row[3],
            "nr_documento": row[4],
            "ds_email": row[5],
            "nr_cep": row[6],
            "nr_cro": row[7],
            "ds_especialidade": row[8]
        }
    except Exception as e:
        print(f"Erro ao buscar contato por ID: {e}")
        return None
    finally:
        if cursor:
            cursor.close()
        conexao.close()

#modifica um contato na tabela
def atualizar_contato(id_contato, tipo_contato, nome, tipo_documento, numero_documento, email, cep, cro="", especialidade=""):
    conexao = conectar()
    if not conexao:
        return

    cursor = None
    try:
        cursor = conexao.cursor()
        sql = """
            UPDATE CONTATO
            SET TP_CONTATO = :1,
                NM_CONTATO = :2,
                TP_DOCUMENTO = :3,
                NR_DOCUMENTO = :4,
                DS_EMAIL = :5,
                NR_CEP = :6,
                NR_CRO = :7,
                DS_ESPECIALIDADE = :8
            WHERE ID_CONTATO = :9
        """
        cursor.execute(sql, (
            tipo_contato,
            nome,
            tipo_documento,
            numero_documento,
            email,
            cep,
            cro,
            especialidade,
            id_contato
        ))
        conexao.commit()

        if cursor.rowcount > 0:
            print("Contato atualizado com sucesso.")
        else:
            print("Contato não encontrado.")
    except Exception as e:
        print(f"Erro ao atualizar contato: {e}")
    finally:
        if cursor:
            cursor.close()
        conexao.close()

#exclui um contato da tabela
def excluir_contato(id_contato):
    conexao = conectar()
    if not conexao:
        return

    cursor = None
    try:
        cursor = conexao.cursor()
        cursor.execute("DELETE FROM CONTATO WHERE ID_CONTATO = :1", (id_contato,))
        conexao.commit()

        if cursor.rowcount > 0:
            print("Contato excluído com sucesso.")
        else:
            print("Contato não encontrado.")
    except Exception as e:
        print(f"Erro ao excluir contato: {e}")
    finally:
        if cursor:
            cursor.close()
        conexao.close()

#procura um contato pelo número do documento dele
def consultar_contato_por_numero_documento(numero_documento):
    conexao = conectar()
    if not conexao:
        return []

    cursor = None
    try:
        cursor = conexao.cursor()
        cursor.execute("""
            SELECT ID_CONTATO, TP_CONTATO, NM_CONTATO, TP_DOCUMENTO, NR_DOCUMENTO, DS_EMAIL, NR_CEP, NR_CRO, DS_ESPECIALIDADE
            FROM CONTATO
            WHERE NR_DOCUMENTO = :1
            ORDER BY ID_CONTATO
        """, (numero_documento,))
        resultados = cursor.fetchall()

        return [
            {
                "id_contato": row[0],
                "tp_contato": row[1],
                "nm_contato": row[2],
                "tp_documento": row[3],
                "nr_documento": row[4],
                "ds_email": row[5],
                "nr_cep": row[6],
                "nr_cro": row[7],
                "ds_especialidade": row[8]
            }
            for row in resultados
        ]
    except Exception as e:
        print(f"Erro na consulta por número de documento: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        conexao.close()

#procura todos os contatos que possuem um tipo de documento providenciado
def consultar_contato_por_tipo_documento(tipo_documento):
    conexao = conectar()
    if not conexao:
        return []

    cursor = None
    try:
        cursor = conexao.cursor()
        cursor.execute("""
            SELECT ID_CONTATO, TP_CONTATO, NM_CONTATO, TP_DOCUMENTO, NR_DOCUMENTO, DS_EMAIL, NR_CEP, NR_CRO, DS_ESPECIALIDADE
            FROM CONTATO
            WHERE UPPER(TP_DOCUMENTO) = UPPER(:1)
            ORDER BY NM_CONTATO
        """, (tipo_documento,))
        resultados = cursor.fetchall()

        return [
            {
                "id_contato": row[0],
                "tp_contato": row[1],
                "nm_contato": row[2],
                "tp_documento": row[3],
                "nr_documento": row[4],
                "ds_email": row[5],
                "nr_cep": row[6],
                "nr_cro": row[7],
                "ds_especialidade": row[8]
            }
            for row in resultados
        ]
    except Exception as e:
        print(f"Erro na consulta por tipo de documento: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        conexao.close()
